notifications:
email: false
language: c
before_install:
    - sudo apt-get update
    - sudo apt-get install -y libc6:i386
    - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2014-q4-major/+download/gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2
    - tar xjf gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2 -C /tmp/
    - sudo cp -f -r /tmp/gcc-arm-none-eabi-4_9-2014q4/* /usr/
    - rm -rf /tmp/gcc-arm-none-eabi-4_9-2014q4 gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2
    - arm-none-eabi-gcc --version ;
compiler: arm-none-eabi-gcc
script: make -j2 firmware

env:
  global:
   - secure: "AfAFHnCYLW7yelVDfj4hsdf/OL/pts8ourjHICaSFcTK5IuHnOiN74dljQMh7Hvv7Ef5Bax1eN5lBO2xOJOl9UfycWrfpeOD4V0kLFCIoHuakXVwAjhjAfttDNYYC2UgrioHLGzG/Y7oo8xZlu4Y0RLO3/wY/CKl9/AkHrUyXng="

addons:
  coverity_scan:
    project:
      name: "Nitrokey/nitrokey-pro-firmware"
      description: "Build submitted via Travis CI"
    notification_email: szczepan@nitrokey.com
    build_command_prepend: "cov-configure --compiler arm-none-gnueabi-gcc --template"
    build_command:   "make -j2 firmware"
    branch_pattern: coverity-scan_2
