notifications:
email: false
language: c
compiler: arm-none-eabi-gcc
before_install:
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    - sudo apt-get update
    - sudo apt-get install -y libc6:i386
    - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2014-q4-major/+download/gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2
    - tar xjf gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2 -C /tmp/
    - sudo cp -f -r /tmp/gcc-arm-none-eabi-4_9-2014q4/* /usr/
    - rm -rf /tmp/gcc-arm-none-eabi-4_9-2014q4 gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2
    - arm-none-eabi-gcc --version ;

env:
  global:
    - secure: "gq/SzGx5U1mcOAukHS1zT+M1Gk8GuBhmlQWPx1RwwjxcADEhpu0eGFqBn3xc69MtLYNM4y0SAanIPQI1OckosTSr70UaNEe4hydK929zv/V6vhT9RI4BZIOW1euXtSxvIz8LJJ0lAHFNP5Hwe2RKuQkumTKAa/Y75cWIJWZDBgE="

addons:
  coverity_scan:
    project:
      name: "Nitrokey/nitrokey-pro-firmware"
      description: "Build submitted via Travis CI"
    notification_email: szczepan@nitrokey.com
    build_command_prepend: "cov-configure --compiler arm-none-gnueabi-gcc --comptype gcc --template; make clean"
    build_command:  "make -j2 firmware"
    branch_pattern: coverity-scan_2

script: make -j2 firmware
